name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test on JDK ${{ matrix.java }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ 17, 21 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Download Spectral executables (Unix/Linux/macOS)
      if: runner.os != 'Windows'
    - name: Download Spectral executables (Unix/Linux/macOS)
      if: runner.os != 'Windows'
      run: |
        chmod +x copy-spectral-executables.sh
        ./copy-spectral-executables.sh
        
    - name: Download Spectral executables (Windows)
      if: runner.os == 'Windows'
      run: .\copy-spectral-executables.ps1
      shell: pwsh
        
    - name: Download Spectral executables (Windows)
      if: runner.os == 'Windows'
      run: .\copy-spectral-executables.ps1
      shell: powershell
        
    - name: Run tests
      run: mvn clean test -B
      
    - name: Build plugin
      run: mvn clean install -B -q
      
    - name: Test plugin functionality
      run: |
        cd test-project
        mvn io.github.ndipiazza:spectral-maven-plugin:validate -B
        
  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Download Spectral executables (Unix/Linux/macOS)
      if: runner.os != 'Windows'
    - name: Download Spectral executables (Unix/Linux/macOS)
      if: runner.os != 'Windows'
      run: |
        chmod +x copy-spectral-executables.sh
        ./copy-spectral-executables.sh
        
    - name: Download Spectral executables (Windows)
      if: runner.os == 'Windows'
      run: .\copy-spectral-executables.ps1
      shell: pwsh
      
        
    - name: Download Spectral executables (Windows)
      if: runner.os == 'Windows'
      run: .\copy-spectral-executables.ps1
      shell: powershell
      
    - name: Build project
      run: mvn clean install -B -q
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: maven-artifacts
        path: |
          spectral-plugin/target/*.jar
          spectral-executables/*/target/*.jar
        retention-days: 30
